version: '3.7'
services:
    nginx:
        image: nginx:1.17
        volumes:
            - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/log/nginx:/var/log/nginx/"
            - "./:/var/www/yii2-library"
        ports:
            - "80:80"
        networks:
            - yii2-library
    php-fpm:
        build: ./docker/bin/php-fpm
        volumes:
            - "./:/var/www/yii2-library"
        networks:
            - yii2-library
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: yii2-library
            MYSQL_ROOT_PASSWORD: Root-123
            MYSQL_USER: user
            MYSQL_PASSWORD: user123
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - "db-yii2-library:/var/lib/mysql"
        networks:
            - yii2-library
    mysql-test:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: yii2-library-test
            MYSQL_ROOT_PASSWORD: Root-123
            MYSQL_USER: user
            MYSQL_PASSWORD: user123
        ports:
            - "127.0.0.1:3307:3306"
        volumes:
            - "db-yii2-library-test:/var/lib/mysql"
        networks:
            - yii2-library
    sphinx:
        build: ./docker/bin/sphinx
        volumes:
            - "sphinx-yii2-library:/opt/sphinx/data"
            - "./docker/log/sphinx:/opt/sphinx/log"
            - "./docker/config/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf"
        links:
            - mysql
        networks:
            - yii2-library
    memcached:
        image: memcached:1.6
        ports:
            - "127.0.0.1:11211:11211"
        command:
            - '--memory-limit=64'
        networks:
            - yii2-library
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '127.0.0.1:8080:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER : root
            PMA_PASSWORD : Root-123
        depends_on:
            - mysql
        networks:
            - yii2-library
    phpmyadmin-test:
        image: phpmyadmin/phpmyadmin
        ports:
            - '127.0.0.1:8081:80'
        environment:
            PMA_HOST: mysql-test
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: Root-123
        depends_on:
            - mysql-test
        networks:
            - yii2-library
networks:
    yii2-library:
volumes:
    db-yii2-library:
    db-yii2-library-test:
    sphinx-yii2-library: